version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/openjdk:11-jdk"
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
      - run:
          name: Bygg
          command: mvn install
      - save_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          name: Setup some ENV
          command: |
            mkdir /tmp/workspace
            echo "DOCKER_TAG=navikt/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_REPONAME}:$COMMIT_SHORT" >> /tmp/workspace/properties.env
            cat /tmp/workspace/properties.env >> $BASH_ENV
      - run:
          name: Build docker image
          command: |
            echo "DOCKER_TAG=$DOCKER_TAG"
            docker build -t docker.pkg.github.com/$DOCKER_TAG .
      - run:
          name: Docker push
          command: |
            echo "DOCKER_TAG=$DOCKER_TAG"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
            echo "Pushing with tag $DOCKER_TAG"
            docker push docker.pkg.github.com/$DOCKER_TAG
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            branches:
              only: master
