version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/openjdk:11-jdk"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Bygg
          command: mvn install
      - run:
          name: Build docker image
          command: |
            export COMMIT_SHORT=$(git rev-parse --short HEAD)
            docker build -t docker.pkg.github.com/navikt/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_REPONAME}:$COMMIT_SHORT .
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            branches:
              only: master
